/**
 * Cloudflare Worker for serving the Quizbase Next.js app.
 *
 * `npm run build` generates an `out/` directory with:
 *   - Static pages:  out/login.html, out/join.html, out/dashboard.html, …
 *   - Dynamic shell pages (from generateStaticParams with placeholder '_'):
 *       out/presenter/_.html              ← /presenter/[sessionId]
 *       out/presenter/_/stats.html        ← /presenter/[sessionId]/stats
 *       out/presenter/edit/_.html         ← /presenter/edit/[pollId]
 *       out/p/_.html                      ← /p/[sessionId]
 *       out/profile/_.html                ← /profile/[userId]
 *   - Static assets: out/_next/static/…
 *
 * The worker:
 *   1. Serves robots.txt and sitemap.xml inline (generated by Next.js at build)
 *   2. Serves static assets directly (JS, CSS, images, fonts, etc.)
 *   3. Maps each dynamic path to its matching shell HTML file
 *   4. Tries the exact .html counterpart for static pages
 *   5. Falls back to index.html for any unmatched path
 */

const DOMAIN = 'quizbase.xn--schchner-2za.de';

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (!env.ASSETS) {
      return new Response('Service unavailable', { status: 503 });
    }

    // Helper: fetch an asset by clean path (no query string)
    const fetchAsset = (path) => {
      const assetUrl = new URL(path, url.origin).toString();
      return env.ASSETS.fetch(new Request(assetUrl, { method: 'GET', headers: request.headers }));
    };

    // 1. Inline robots.txt (avoids needing a separate file in out/)
    if (url.pathname === '/robots.txt') {
      return new Response(
        `User-agent: *\nAllow: /\nCrawl-delay: 1\n\nSitemap: https://${DOMAIN}/sitemap.xml\nHost: https://${DOMAIN}`,
        { headers: { 'Content-Type': 'text/plain' } }
      );
    }

    // 2. Inline sitemap.xml
    if (url.pathname === '/sitemap.xml') {
      const base = `https://${DOMAIN}`;
      const now = new Date().toISOString();
      const urls = [
        { loc: base, freq: 'weekly', priority: '1.0' },
        { loc: `${base}/join`, freq: 'monthly', priority: '0.8' },
        { loc: `${base}/login`, freq: 'monthly', priority: '0.7' },
        { loc: `${base}/discover`, freq: 'daily', priority: '0.9' },
        { loc: `${base}/analytics`, freq: 'weekly', priority: '0.6' },
        { loc: `${base}/legal`, freq: 'yearly', priority: '0.2' },
        { loc: `${base}/privacy`, freq: 'yearly', priority: '0.2' },
        { loc: `${base}/impressum`, freq: 'yearly', priority: '0.2' },
        { loc: `${base}/datenschutz`, freq: 'yearly', priority: '0.2' },
        { loc: `${base}/design`, freq: 'monthly', priority: '0.5' },
      ];
      const xml =
        `<?xml version="1.0" encoding="UTF-8"?>\n` +
        `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
        urls
          .map(
            (u) =>
              `  <url>\n    <loc>${u.loc}</loc>\n    <lastmod>${now}</lastmod>\n` +
              `    <changefreq>${u.freq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`
          )
          .join('\n') +
        `\n</urlset>`;
      return new Response(xml, {
        headers: { 'Content-Type': 'application/xml; charset=utf-8', 'Cache-Control': 'public, max-age=86400' },
      });
    }

    // 3. Try direct asset first (handles _next/static/…, images, fonts, etc.)
    const directResponse = await fetchAsset(url.pathname);
    if (directResponse.status === 200) {
      return directResponse;
    }

    // 4. Determine which HTML file to serve based on the request path
    const cleanPath = url.pathname.replace(/\/$/, '') || '/';
    const parts = cleanPath.split('/').filter(Boolean);

    let htmlPath;

    if (cleanPath === '/') {
      htmlPath = '/index.html';
    } else if (parts[0] === 'presenter') {
      if (parts[1] === 'edit' && parts.length >= 3) {
        // /presenter/edit/<pollId>  →  shell: /presenter/edit/_.html
        htmlPath = '/presenter/edit/_.html';
      } else if (parts.length >= 3 && parts[2] === 'stats') {
        // /presenter/<sessionId>/stats  →  shell: /presenter/_/stats.html
        htmlPath = '/presenter/_/stats.html';
      } else if (parts.length >= 2) {
        // /presenter/<sessionId>  →  shell: /presenter/_.html
        htmlPath = '/presenter/_.html';
      } else {
        // /presenter (static redirect page)
        htmlPath = '/presenter.html';
      }
    } else if (parts[0] === 'p' && parts.length >= 2) {
      // /p/<sessionId>  →  shell: /p/_.html
      htmlPath = '/p/_.html';
    } else if (parts[0] === 'profile' && parts.length >= 2) {
      // /profile/<userId>  →  shell: /profile/_.html
      htmlPath = '/profile/_.html';
    } else {
      // Static page: /login → /login.html, /dashboard → /dashboard.html, etc.
      htmlPath = `${cleanPath}.html`;
    }

    const pageResponse = await fetchAsset(htmlPath);
    if (pageResponse.status === 200) {
      return pageResponse;
    }

    // 5. Final fallback: serve the root index
    return fetchAsset('/index.html');
  },
};
